# Generated by Django 3.1 on 2020-08-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='activities.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Iniciada', 'Iniciada'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], max_length=50),
        ),
    ]
