# Generated by Django 3.1 on 2020-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20200811_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
